name: GH and Hex.pm Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    uses: TanklesXL/gleam_actions/.github/workflows/release.yaml@main
    secrets: inherit
    with:
      gleam_version: 1.3.1
      erlang_version: 27
      test_erlang: true
      test_node: true
